/**
 * BONK! — Service worker: offline play + instant repeat launches
 * ---------------------------------------------------------------
 * Strategy
 *   • install  : pre-cache the app shell (html, css, js, level data, every image) — the list is generated by
 *                tools/bump.py from index.html + assets/, so it never drifts from the real files.
 *   • fetch    : same-origin GET → cache-first (shell is immutable per VERSION; a new version = new cache name).
 *                Anything else (leaderboard API, fonts) → network only.
 *   • activate : delete caches of older versions, take control right away.
 * The page listens for 'controllerchange' and shows a "new version — tap to reload" toast (src/services/pwa.js).
 */
const VERSION = '0.20.0';
const CACHE = 'bonk-' + VERSION;
const SHELL = [
  './',
  './index.html',
  './manifest.webmanifest',
  'src/app.js',
  'src/audio/music.js',
  'src/audio/sfx.js',
  'src/core/assets.js',
  'src/core/config.js',
  'src/core/dom.js',
  'src/core/events.js',
  'src/core/input.js',
  'src/core/perf.js',
  'src/data/goals.js',
  'src/data/items.js',
  'src/data/levels.js',
  'src/game/ambient.js',
  'src/game/background.js',
  'src/game/effects.js',
  'src/game/ftue.js',
  'src/game/game.js',
  'src/game/mechanics.js',
  'src/game/puppy.js',
  'src/game/rig.js',
  'src/game/spawner.js',
  'src/scenes/home.js',
  'src/scenes/play.js',
  'src/services/ads.js',
  'src/services/analytics.js',
  'src/services/daily.js',
  'src/services/flags.js',
  'src/services/leaderboard.js',
  'src/services/nav.js',
  'src/services/pwa.js',
  'src/services/remix.js',
  'src/services/save.js',
  'src/services/shop.js',
  'src/services/store.js',
  'src/services/wallet.js',
  'src/ui/hud.js',
  'src/ui/modals.js',
  'styles/main.css',
  'styles/base.css',
  'styles/home.css',
  'styles/hud.css',
  'styles/modals.css',
  'data/levels/L01.json',
  'data/levels/L02.json',
  'data/levels/L03.json',
  'data/levels/L04.json',
  'data/levels/L05.json',
  'data/levels/L06.json',
  'data/levels/L07.json',
  'data/levels/L08.json',
  'data/levels/L09.json',
  'data/levels/L10.json',
  'data/levels/L11.json',
  'data/levels/L12.json',
  'data/levels/L13.json',
  'data/levels/L14.json',
  'data/levels/L15.json',
  'data/levels/L16.json',
  'data/levels/index.json',
  'assets/icons/apple-touch-icon.png',
  'assets/icons/favicon.png',
  'assets/icons/icon-192.png',
  'assets/icons/icon-512.png',
  'assets/icons/maskable-512.png',
  'assets/images/ambient/bird_sheet.webp',
  'assets/images/ambient/car0.webp',
  'assets/images/ambient/car1.webp',
  'assets/images/ambient/car2.webp',
  'assets/images/ambient/squirrel.webp',
  'assets/images/ambient/walker0_sheet.webp',
  'assets/images/ambient/walker1_sheet.webp',
  'assets/images/bg/beach_far.webp',
  'assets/images/bg/beach_mid.webp',
  'assets/images/bg/cloud0.webp',
  'assets/images/bg/cloud1.webp',
  'assets/images/bg/cloud2.webp',
  'assets/images/bg/foreground_wide.webp',
  'assets/images/bg/forest_far.webp',
  'assets/images/bg/forest_mid.webp',
  'assets/images/bg/meadow.webp',
  'assets/images/bg/mountains.webp',
  'assets/images/bg/park_far.webp',
  'assets/images/bg/park_mid.webp',
  'assets/images/bg/road.webp',
  'assets/images/bg/sky.webp',
  'assets/images/bg/trees.webp',
  'assets/images/bg/village.webp',
  'assets/images/bg/water_mask.webp',
  'assets/images/home/dog_sit.webp',
  'assets/images/home/dog_sit_b.webp',
  'assets/images/home/logo.webp',
  'assets/images/home/plate.webp',
  'assets/images/items/bomb.webp',
  'assets/images/items/bone.webp',
  'assets/images/items/coin.webp',
  'assets/images/items/goldbone.webp',
  'assets/images/items/magnet.webp',
  'assets/images/items/rock.webp',
  'assets/images/items/shield.webp',
  'assets/images/items/star.webp',
  'assets/images/levels/thumb_1.webp',
  'assets/images/levels/thumb_10.webp',
  'assets/images/levels/thumb_11.webp',
  'assets/images/levels/thumb_12.webp',
  'assets/images/levels/thumb_13.webp',
  'assets/images/levels/thumb_14.webp',
  'assets/images/levels/thumb_15.webp',
  'assets/images/levels/thumb_16.webp',
  'assets/images/levels/thumb_2.webp',
  'assets/images/levels/thumb_3.webp',
  'assets/images/levels/thumb_4.webp',
  'assets/images/levels/thumb_5.webp',
  'assets/images/levels/thumb_6.webp',
  'assets/images/levels/thumb_7.webp',
  'assets/images/levels/thumb_8.webp',
  'assets/images/levels/thumb_9.webp',
  'assets/images/puppy/puppy_bonk.webp',
  'assets/images/puppy/puppy_dizzy.webp',
  'assets/images/puppy/puppy_yay.webp',
  'assets/images/puppy/rig/ear.webp',
  'assets/images/puppy/rig/head.webp',
  'assets/images/puppy/rig/leg_front.webp',
  'assets/images/puppy/rig/leg_hind.webp',
  'assets/images/puppy/rig/mouth.webp',
  'assets/images/puppy/rig/tail.webp',
  'assets/images/puppy/rig/torso.webp',
  'assets/images/ui/heart.webp',
  'assets/images/ui/heart_empty.webp',
  'assets/images/ui/lock.webp',
  'assets/images/ui/star_gold.webp',
  'assets/images/ui/star_grey.webp',
  'assets/images/ui/trophy.webp'
];   // filled by tools/bump.py

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL.map(u => new Request(u, { cache: 'reload' })))).then(() => self.skipWaiting()));
});
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k.startsWith('bonk-') && k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', e => {
  const req = e.request; if (req.method !== 'GET') return;
  const url = new URL(req.url); if (url.origin !== location.origin) return;
  // strip our own cache-busting query (?v=, ?a=, ?source=) so one cached copy serves every tag
  const key = new Request(url.origin + url.pathname, { headers: req.headers, mode: 'same-origin' });
  e.respondWith(caches.match(key, { ignoreSearch: true }).then(hit => hit || fetch(req).then(res => {
    if (res.ok && res.type === 'basic') { const copy = res.clone(); caches.open(CACHE).then(c => c.put(key, copy)); }
    return res;
  }).catch(() => url.pathname.endsWith('/') || url.pathname.endsWith('.html') ? caches.match('./index.html', { ignoreSearch: true }) : undefined)));
});
self.addEventListener('message', e => { if (e.data === 'skipWaiting') self.skipWaiting(); });
